import "../styles/globals.css";
import 'normalize.css'

import { lato, oswald } from '../utils/fonts'

import StyledComponentsRegistry from '../lib/registry'

export const metadata = {
  title: "Garden4Less - Garden Solutions in West Lothian",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <body className={`${lato.variable} ${oswald.variable}`}>
          {children}
        </body>
      </StyledComponentsRegistry>
    </html>
  );
}
